/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Articulo;

import controlador.Coordinador;
import javax.swing.JOptionPane;
import modelo.ArticuloVO;

/**
 *
 * @author Daniela
 */
public class VentanaEdicionArticulo extends javax.swing.JFrame {
        private Coordinador miCoordinador;
    /**
     * Creates new form VentanaEdicionArticulo
     */
    public VentanaEdicionArticulo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoArt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDetalleArt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCategoriaArt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadExistenteArt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioArt = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        botonGuardarA = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edicion de Articulo");

        jLabel1.setText("Codigo de Articulo :");

        jLabel2.setText("Detalle de Articulo :");

        txtDetalleArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetalleArtActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria de Articulo  :");

        jLabel4.setText("Cantidad Existente de Articulo :");

        jLabel5.setText("Precio de Articulo :");

        txtPrecioArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioArtActionPerformed(evt);
            }
        });

        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardarA.setText("GUARDAR");
        botonGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarAActionPerformed(evt);
            }
        });

        botonActualizar.setText("ACTUALIZAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoArt)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDetalleArt)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCategoriaArt)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(txtCantidadExistenteArt)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecioArt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGuardarA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDetalleArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoriaArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadExistenteArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonGuardarA)
                    .addComponent(botonActualizar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDetalleArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetalleArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetalleArtActionPerformed

    private void txtPrecioArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioArtActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        VentanaArticulo vArti = new VentanaArticulo();
        vArti.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarAActionPerformed
        ArticuloVO artVO = new ArticuloVO();
        miCoordinador = new Coordinador();

        int codigo = Integer.parseInt(txtCodigoArt.getText().trim());
        String detalle = txtDetalleArt.getText().trim();
        String categoria = txtCategoriaArt.getText().trim();
        int cantExistencia = Integer.parseInt(txtCantidadExistenteArt.getText().trim());
        int precioVenta = Integer.parseInt(txtPrecioArt.getText().trim());

        artVO.setCodigo(codigo);
        artVO.setDetalle(detalle);
        artVO.setCategoria(categoria);
        artVO.setCantidadExistente(cantExistencia);
        artVO.setPrecioVenta(precioVenta);

        if ((artVO.getCodigo() <= 0
                || artVO.getDetalle() == null || artVO.getDetalle().equals("")
                || artVO.getCategoria() == null || artVO.getCategoria().equals("")
                || artVO.getCantidadExistente() <= 0
                || artVO.getPrecioVenta() <= 0)) {

            JOptionPane.showMessageDialog(rootPane, "Error en los campos", "", JOptionPane.ERROR_MESSAGE);

        } else {
            if (miCoordinador.agregarArticulo(artVO)) {
                JOptionPane.showMessageDialog(rootPane, "Articulo agregado", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Articulo no se pudo agregar", "", JOptionPane.ERROR_MESSAGE);
            }
        }

        VentanaArticulo ventanita = new VentanaArticulo();
        ventanita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonGuardarAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEdicionArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEdicionArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEdicionArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEdicionArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEdicionArticulo().setVisible(true);
            }
        });
    }

    void pasarInformacionA(int codigo, String detalle, String categoria, int cantidadExistencia, int precioVenta) {
        this.txtCodigoArt.setText(codigo+"");
        this.txtDetalleArt.setText(detalle);
        this.txtCategoriaArt.setText(categoria);
        this.txtCantidadExistenteArt.setText(cantidadExistencia+"");
        this.txtPrecioArt.setText(precioVenta+"");
    }
    
    void ocultarBotonActualizar(){
        this.botonActualizar.setVisible(false);
        this.botonGuardarA.setVisible(true);
    }

    void ocultarBotonGuardar() {
        this.botonActualizar.setVisible(true);
        this.botonGuardarA.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardarA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCantidadExistenteArt;
    private javax.swing.JTextField txtCategoriaArt;
    private javax.swing.JTextField txtCodigoArt;
    private javax.swing.JTextField txtDetalleArt;
    private javax.swing.JTextField txtPrecioArt;
    // End of variables declaration//GEN-END:variables
}
