/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Articulo;

import controlador.Coordinador;
import javax.swing.JOptionPane;
import modelo.ArticuloVO;
import modelo.ClienteVO;
import vista.Cliente.VentanaCliente;
import vista.Cliente.VentanaEdicionCliente;
import vista.Venta.VentanaVenta;

/**
 *
 * @author Daniela
 */
public class VentanaDatoArticulo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDatoArticulo
     */
    public VentanaDatoArticulo() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        //aca setear campos obtenidos del vo
        //txtCodigoArticulo.setText("ASDASDASD");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDetalleA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCategoriaA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioA = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo de Articulo :");

        txtCodigoA.setEditable(false);
        txtCodigoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoAActionPerformed(evt);
            }
        });

        jLabel2.setText("Detalle de Articulo :");

        txtDetalleA.setEditable(false);

        jLabel3.setText("Categoria de Articulo :");

        txtCategoriaA.setEditable(false);

        jLabel4.setText("Cantidad Existente de Articulo :");

        txtCantA.setEditable(false);
        txtCantA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantAActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio de Articulo");

        txtPrecioA.setEditable(false);

        botonEliminar.setText("ELIMINAR");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonEditar.setText("EDITAR");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminar)
                        .addGap(66, 66, 66)
                        .addComponent(botonEditar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodigoA)
                        .addComponent(txtDetalleA)
                        .addComponent(txtCategoriaA)
                        .addComponent(txtCantA)
                        .addComponent(txtPrecioA, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDetalleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonEditar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantAActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        VentanaEdicionArticulo edArt = new VentanaEdicionArticulo();
        //traspasar informacion a ventana de edicion
        edArt.pasarInformacionA(Integer.parseInt(txtCodigoA.getText())
                , txtDetalleA.getText()
                , txtCategoriaA.getText()
                , Integer.parseInt(txtCantA.getText())
                , Integer.parseInt(txtPrecioA.getText()));
        //edArt.setVisible(true);
        edArt.ocultarBotonGuardar();
        edArt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void txtCodigoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAActionPerformed
        
    }//GEN-LAST:event_txtCodigoAActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int codigo = Integer.parseInt(txtCodigoA.getText());
        Coordinador miCoordinador = new Coordinador();
        boolean resultado = miCoordinador.eliminarArticulo(codigo);
        if (resultado) {
            JOptionPane.showMessageDialog(rootPane, "Articulo eliminado", "", JOptionPane.INFORMATION_MESSAGE);
            VentanaArticulo vArt = new VentanaArticulo();
            vArt.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Articulo no se pudo eliminar", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatoArticulo().setVisible(true);
                
            }
        });
    }
    
    void pasarCodigo(int codigo) {
        Coordinador miCoordinador = new Coordinador();
        ArticuloVO articuloVO = new ArticuloVO();
        articuloVO = miCoordinador.obtenerArticulo(codigo);
        
        
        txtCodigoA.setText(articuloVO.getCodigo()+"");
        txtDetalleA.setText(articuloVO.getDetalle());
        txtCategoriaA.setText(articuloVO.getCategoria());
        txtCantA.setText(articuloVO.getCantidadExistente()+"");
        txtPrecioA.setText(articuloVO.getPrecioVenta()+"");
                
        if ( txtDetalleA == null || txtDetalleA.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO ARTICULO", "", JOptionPane.ERROR_MESSAGE);
            VentanaArticulo vArticulo = new VentanaArticulo();
            vArticulo.setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCantA;
    private javax.swing.JTextField txtCategoriaA;
    private javax.swing.JTextField txtCodigoA;
    private javax.swing.JTextField txtDetalleA;
    private javax.swing.JTextField txtPrecioA;
    // End of variables declaration//GEN-END:variables
}

